### ISSUE TITLE
keyboard-only build

### ISSUE THREAD

**Issue by drlkf** [kbjunky/Chordie#3]
Hello!
I'm currently doing a keyboard-only build (10 keys, no trackball, no rotary encoder), and I'm not quite sure how to finish my build, all the instructions to plug the ProMicro are related to the trackball sensor and the rotary encoder, so I don't know how I'm supposed to link mine to one of the expanders, I'm actually perplex as to whether or not I need the ProMicro at all, but I don't see how to plug the keyboard to the computer without it so I'm guessing it's necessary. Could you enlighten me?
Thanks!

**Comment by kbjunky** [comment]
On the left side you have to connect switches to the expander as per instruction and then SDA/SCL/VCC/GND from the expander to the audio jack socket. On the right side you do  the same and then also SDA/SCL/VCC/GND to the corresponding pins on the ProMicro.

**Comment by drlkf** [comment]
Great, thanks!
